# Generated by Django 2.0.5 on 2018-07-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplan',
            unique_together={('user', 'title')},
        ),
    ]
