# Generated by Django 2.0.5 on 2018-07-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('read_user_profile', '读取用户表'),), 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='ops_user_profile',
        ),
    ]
