# Generated by Django 2.0.5 on 2018-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180711_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/%Y/%m'),
        ),
    ]
