# Generated by Django 2.0.5 on 2018-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='计划标题')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('all_day', models.SmallIntegerField(blank=True, null=True, verbose_name='是否全天')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='颜色')),
            ],
        ),
    ]
