# Generated by Django 2.0.5 on 2018-06-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleModuleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_user', models.CharField(max_length=50, verbose_name='操作用户')),
                ('ans_remote_ip', models.GenericIPAddressField(verbose_name='操作用户IP')),
                ('ans_module', models.CharField(max_length=100, verbose_name='模块名称')),
                ('ans_args', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='模块参数')),
                ('ans_server', models.TextField(verbose_name='服务器')),
                ('ans_result', models.TextField(verbose_name='执行结果')),
                ('ans_datetime', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'Ansible模块执行记录表',
                'verbose_name_plural': 'Ansible模块执行记录表',
                'db_table': 'ops_ansible_module_log',
                'permissions': (('can_read_ansible_module_log', '读取Ansible模块执行记录权限'), ('can_change_ansible_module_log', '更改Ansible模块执行记录权限'), ('can_add_ansible_module_log', '添加Ansible模块执行记录权限'), ('can_delete_ansible_module_log', '删除Ansible模块执行记录权限')),
            },
        ),
    ]
