# Generated by Django 2.0.5 on 2018-07-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansiblemodulelog',
            options={'verbose_name': 'Ansible模块执行记录表', 'verbose_name_plural': 'Ansible模块执行记录表'},
        ),
    ]
