# Generated by Django 2.0.5 on 2018-07-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='资产管理员'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_cabinets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Cabinets', verbose_name='所在机柜'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.IDC', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_project',
            field=models.ManyToManyField(blank=True, to='assets.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.AssetProvider', verbose_name='供应商'),
        ),
        migrations.AlterUniqueTogether(
            name='ramassets',
            unique_together={('asset', 'ram_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='networkcardassets',
            unique_together={('asset', 'network_card_mac')},
        ),
        migrations.AlterUniqueTogether(
            name='diskassets',
            unique_together={('asset', 'disk_slot')},
        ),
    ]
