# Generated by Django 2.0.5 on 2018-07-21 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_log', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
    ]
