# Generated by Django 2.0.5 on 2018-07-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180705_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='数据库、中间件等', max_length=32, verbose_name='业务名称')),
                ('business_memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='基本描述')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Project')),
            ],
        ),
        migrations.AddField(
            model_name='serverassets',
            name='auth_type',
            field=models.SmallIntegerField(choices=[(0, '密钥认证'), (1, '账户密码')], default=0, verbose_name='认证方式'),
        ),
    ]
