# Generated by Django 2.0.5 on 2018-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180705_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverassets',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='serverassets',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='serverassets',
            name='port',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='SSH端口'),
        ),
        migrations.AlterField(
            model_name='serverassets',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名称'),
        ),
    ]
