# Generated by Django 2.0.5 on 2018-07-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180705_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'permissions': (('can_read_business', '读取业务权限'), ('can_change_business', '更改业务权限'), ('can_add_business', '添加业务权限'), ('can_delete_business', '删除业务权限')), 'verbose_name': '业务表', 'verbose_name_plural': '业务表'},
        ),
        migrations.AlterModelTable(
            name='business',
            table='ops_business',
        ),
    ]
