# Generated by Django 2.0.5 on 2018-07-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180706_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='asset_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '已上线'), (1, '已下线'), (2, '故障中'), (3, '未使用')], null=True, verbose_name='状态'),
        ),
    ]
