# Generated by Django 2.0.5 on 2018-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180714_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprovider',
            name='asset_provider_telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='支持电话'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='idc_telephone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='支持电话'),
        ),
    ]
