# Generated by Django 2.0.5 on 2018-07-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180714_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='city',
        ),
    ]
