# Generated by Django 2.0.5 on 2018-06-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_ip', models.GenericIPAddressField(unique=True, verbose_name='内网IP')),
                ('ssh_port', models.IntegerField(null=True, verbose_name='ssh登录的端口')),
                ('ssh_user', models.CharField(max_length=32, null=True, verbose_name='ssh登录的用户')),
                ('ssh_passwd', models.CharField(max_length=64, null=True, verbose_name='ssh登录的用户密码')),
                ('system_ver', models.CharField(default='', max_length=64, verbose_name='操作系统版本')),
                ('hostname', models.CharField(default='', max_length=64, verbose_name='主机名')),
                ('host_type', models.SmallIntegerField(choices=[(0, '物理机'), (1, '阿里云'), (2, '虚拟机')], default=0, verbose_name='主机类型')),
                ('sn', models.CharField(default='', max_length=64, verbose_name='主机序号')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='制造商')),
                ('server_model', models.CharField(max_length=64, verbose_name='服务器型号')),
                ('mac', models.CharField(max_length=32, verbose_name='MAC地址')),
                ('total_mem', models.IntegerField(verbose_name='内存容量，单位(M)')),
                ('cpu_counts', models.SmallIntegerField(verbose_name='CPU逻辑数量')),
                ('cpu_model', models.CharField(max_length=64, verbose_name='CPU型号')),
                ('total_disk', models.CharField(max_length=16, verbose_name='硬盘容量')),
                ('scan_datetime', models.DateTimeField(auto_now_add=True, verbose_name='扫描日期')),
            ],
            options={
                'verbose_name': '扫描信息表',
                'verbose_name_plural': '扫描信息表',
                'db_table': 'hostinfo',
                'permissions': (('can_read_hostinfo', '读取扫描资产权限'), ('can_change_hostinfo', '更改扫描资产权限'), ('can_add_hostinfo', '添加扫描资产权限'), ('can_delete_hostinfo', '删除扫描资产权限')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='hostinfo',
            unique_together={('hostname', 'mac')},
        ),
    ]
