# Generated by Django 2.0.5 on 2018-06-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='外网IP'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssh_port',
            field=models.SmallIntegerField(null=True, verbose_name='ssh登录的端口'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='total_mem',
            field=models.SmallIntegerField(verbose_name='内存容量，单位(M)'),
        ),
    ]
