# Generated by Django 2.0.5 on 2018-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0002_auto_20180608_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='ssh_passwd',
            field=models.CharField(max_length=64, null=True, verbose_name='ssh登录密码'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssh_port',
            field=models.SmallIntegerField(null=True, verbose_name='ssh登录端口'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ssh_user',
            field=models.CharField(max_length=32, null=True, verbose_name='ssh登录用户'),
        ),
    ]
