# Generated by Django 2.0.5 on 2018-07-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0003_auto_20180609_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinfo',
            options={'verbose_name': '扫描信息表', 'verbose_name_plural': '扫描信息表'},
        ),
        migrations.AlterModelTable(
            name='hostinfo',
            table='ops_hostinfo',
        ),
    ]
